### ISSUE TITLE
UI/UX - Dark Theme / Dark Mode Glitch

### ISSUE THREAD

**Issue by Kryptopaid** [bearby-wallet/bearby-extension#1]
When the dark mode is activated (would it be from the system one, or the browser one) it is not possible to read the text in settings, or even for creating a new account (impossible to read the 12 words). Example here:
![image](https://user-images.githubusercontent.com/81397547/193625977-38ca7989-ab5f-4e3d-8fcd-a2c7adea1f05.png)
![image](https://user-images.githubusercontent.com/81397547/193626100-a5e67ce7-af81-4cc8-be16-d629f436d39c.png)
![image](https://user-images.githubusercontent.com/81397547/193626163-faa830de-e1a0-4825-b50e-87ecbdf0b232.png)

**Comment by hicaru** [comment]
yes dark colors in developing.
