### ISSUE TITLE
XMA (MAS?) amount?

### ISSUE THREAD

**Issue by rykcod** [bearby-wallet/bearby-extension#20]
Maybe an issue to show XMA (MAS?) amount? Maybe when the amoutn is not an integer?

![Screenshot 2022-10-10 183009](https://user-images.githubusercontent.com/32191714/194913518-0b4c116a-e5d2-42e8-bde8-1e77e514d4a8.png)
![Screenshot 2022-10-10 183354](https://user-images.githubusercontent.com/32191714/194913663-dbf1a4fa-3bbc-476c-8c7c-981e3a36412f.png)

**Comment by hicaru** [comment]
Hello, it becouse the jsonRPC server had been changed `getAddresses` interface, it already fixed in new version.

**Comment by rykcod** [comment]
You are right! Same problem with my docker image automation on this v15 release xD
Good luck guy :)
