### ISSUE TITLE
Consult history

### ISSUE THREAD

**Issue by rykcod** [bearby-wallet/bearby-extension#22]
Need to find reveiver address + trx id + Date & time of trx
Today no detail by cliking on the trx

Just a basic feedback, i know you are working and its just the begin
![Screenshot 2022-10-10 184519](https://user-images.githubusercontent.com/32191714/194915443-d0a8ac43-7107-4e9d-a67f-6b19fa4ab762.png)

**Comment by hicaru** [comment]
Thanks for your issue, i will add it in new release

**Comment by hicaru** [comment]
fixed https://github.com/bearby-wallet/bearby-extension/releases/tag/0.0.5
