### ISSUE TITLE
pubKey request

### ISSUE THREAD

**Issue by hicaru** [bearby-wallet/bearby-extension#54]
* need add connection verify

**Comment by mopo06** [comment]
Hello, I have a problem with my wallet. I have private keys for the wallet, and I added another account to the wallet, but I didn't receive the private key. Can I recover the account within the wallet?

**Comment by hicaru** [comment]
> Hello, I have a problem with my wallet. I have private keys for the wallet, and I added another account to the wallet, but I didn't receive the private key. Can I recover the account within the wallet?

hello for each account wallet create privateKey you can export it in security page!
