### ISSUE TITLE
seed phrase got me another wallet address

### ISSUE THREAD

**Issue by camsvids** [bearby-wallet/bearby-extension#55]
hi!

my laptop was broken, so i bought new one, restored all my extensions but when I was trying to restore Bearby wallet and put seed phrase, it showed me new wallet address, not the one i put on Massa site. Who can help me to fix it?

**Comment by hicaru** [comment]
Hello, nobody can help you if you input wrong words! 
make sure you are inputing right words! Any incorrect char or different word, ordering maybe extra space will restore different wallet!
