### ISSUE TITLE
Wrong amount displayed when interacting with dApp

### ISSUE THREAD

**Issue by vlouppe** [bearby-wallet/bearby-extension#61]
When i buy an NFT on the Purrfect Univiserse buildnet demo (https://massa-marketplace.vercel.app/collection/charlie) the amount displayed in the bearby popup is 0

![Screenshot 2024-02-12 at 12 26 24](https://github.com/bearby-wallet/bearby-extension/assets/592836/4298f65e-b6fa-41ed-bf5a-c64ce8c5ca40)
 
However the amount is good in the operation send in the BC.

This issue does not occur with massa station wallet.

**Comment by hicaru** [comment]
Hello, thanks for your great issue, i will fix it in new release
