### ISSUE TITLE
wallet not enabled

### ISSUE THREAD

**Issue by felipeyk2** [bearby-wallet/bearby-extension#63]
I have a problem with my wallet, I have 1800 massa that I cannot transfer, I have the latest update, I am using the mainet the correct rpc, and when I try to send it says node out of storage the hash, I wanted to export the wallet with my private key and When I export it I get the message: GUARD wallet is note enabled, then I use the seed phrase and it opens another wallet that is not mine. And on Telegram I have been looking for a solution for more than 1 month and no one tells me anything. This is the address AU1gQgf2gWYhwBKf9JW61AYQySRsM2hhe8d6z4dQw2L5GQXtpVQG

I hope you can find me a solution

**Comment by hicaru** [comment]
hello try reset nodes in networks, the error `node out of storage the hash` from node, it has nothing to do with bearby wallet and out of my control
