### ISSUE TITLE
Connection not related to account:

### ISSUE THREAD

**Issue by Ben-Rey** [bearby-wallet/bearby-extension#67]
Example:
I am currently using a second account that isn't linked to my dApp, yet I can observe the connection within the general settings 

![Capture d’écran 2024-03-11 à 11 43 45](https://github.com/bearby-wallet/bearby-extension/assets/44082144/4e18c9ba-3acc-42e1-9fad-e3afe785cec9)

Here no accounts are selected:
![Capture d’écran 2024-03-11 à 11 48 50](https://github.com/bearby-wallet/bearby-extension/assets/44082144/ab0254af-56c9-42ba-a69f-1fe0e9ad2842)

![Connections](https://github.com/bearby-wallet/bearby-extension/assets/44082144/372680d6-1401-4484-8dfb-66f11f28cab9)

I believe that connection settings should be specific to each account rather than being accessible in the global settings.

**Comment by hicaru** [comment]
hello you can click on top icon with connection, there you can see which accounts are connecting

**Comment by Ben-Rey** [comment]
Fixed thanks
