### ISSUE TITLE
Enhancing DApp Usability with Improved Account Switch Detection

### ISSUE THREAD

**Issue by Ben-Rey** [bearby-wallet/bearby-extension#68]
Currently, our dApp does not detect when a user switches accounts if the newly selected account has not been previously connected to the dApp. This limitation hinders our ability to prompt users for connection permissions after they switch accounts, potentially affecting user experience and dApp functionality.

### Proposed Solutions:

`Enable Account Switch Detection for Unconnected Accounts`: Allow the dApp to detect when users switch to an account that hasn't been connected yet. This would enable the dApp to prompt users to connect the new account, improving usability and engagement.

`Prompt for Connection on Account Switch via Wallet`: Automatically prompt users to connect their new account through their wallet when they switch accounts. This ensures a smoother user experience by facilitating immediate interaction with the dApp using the newly selected account.

**Comment by hicaru** [comment]
Thanks for your issue, i will fix it in new release.
