### ISSUE TITLE
Account Disconnection Not Preventing Smart Contract Calls

### ISSUE THREAD

**Issue by Ben-Rey** [bearby-wallet/bearby-extension#69]
Description:

Encountering a malfunction when attempting to unlink (uncheck) an account from the list of accounts connected to the dApp. Despite successfully unchecking an account, transactions initiated by this account still proceed but ultimately result in an error.

Steps to Reproduce:

Navigate to the list of accounts linked to the dApp.
Uncheck an account to unlink it from the dApp.
Attempt to initiate a transaction with the unlinked account.
Expected Behavior:

Upon unchecking an account, it should be completely disconnected from the dApp, preventing any transactions from being initiated or processed.

Actual Behavior:

Transactions can still be triggered by the unlinked account, leading to an error. This indicates that the account is not fully disconnected, suggesting a disconnection issue in the unlinking process.

Impact:

This issue impacts user experience and dApp security by allowing potentially unauthorized transactions to be initiated, only to fail, which could lead to confusion and a lack of trust in the dApp's account management system.

Suggested Fix:

Review and fix the logic handling the unlinking of accounts to ensure that once an account is unchecked, it is fully disconnected and unable to initiate any transactions or the triggering of connection requests for accounts that are not connected.

![Vite + React + TS](https://github.com/bearby-wallet/bearby-extension/assets/44082144/ed1f7ec3-ebcd-497a-acc0-aa03986eba2a)

**Comment by hicaru** [comment]
Thanks for your issue, i will fix it in new release

**Comment by hicaru** [comment]
Sorry but i cannot repeat the issue on my side, can you help make video or provide more details?
