### ISSUE TITLE
не отображаются монеты 

### ISSUE THREAD

**Issue by Irishka1963** [bearby-wallet/bearby-extension#73]
в кошельке не отображаются монеты.хотя раньше были...оба адреса связаны.но отображаются монеты только на одном.основном адресе.который сейчас открывается только д

ля просмотра и с него монеты не выводятся..![image](https://github.com/bearby-wallet/bearby-extension/assets/102864841/1d5dff21-a5e9-4b42-96f7-6ccb4fd976c1)

**Comment by Irishka1963** [comment]
монеты раньше отображались на 1аккаунте.суйчас отображаются на другом.основном адресе.но он только для просмотра и вывести с него монеты не могу...пожалуйстап.омогите

**Comment by hicaru** [comment]
Track 0 вы добавили по адресу, что бы отправить вам нужно именно владеть им, то есть иметь приватный ключ от него!

**Comment by hicaru** [comment]
монеты могут не отображаться по 2 причинам
 * у вас их нет
 * * у вас упал узел который вы выбрали или он отстает
