### ISSUE TITLE
Can't export private key.

### ISSUE THREAD

**Issue by ea19ea** [bearby-wallet/bearby-extension#74]
When I try to export my private key, it gives me the private key of a different address.

**Comment by hicaru** [comment]
show me details, how did you export it

**Comment by ea19ea** [comment]
1. Open Bearby extension.
2. Click on gear icon.
3. Click on Seucrity & Privacy -> Export under Show Private Keys.
4. Enter password, click on enter.
The address shown in the pop-up doesn't match the address shown in the home page of the extension. And when I import this private key to the Massa Station wallet the address shown is the address I see when I reveal private key in the Bearby wallet not what I see in the home page of Bearby extension.

**Comment by hicaru** [comment]
hello, thanks for your issue, i have tested it many times, on Mac os and Linux system and it works fine for me! Please could you provide more information for catch a bug?

**Comment by ea19ea** [comment]
Looks like the way private keys are generated changed sometime before mainnet. I installed Bearby about a year ago I think and didn't know about this change. So now I don't have access to the address that I sent my funds to because I don't have the private keys of the address Bearby shows.
![a](https://github.com/bearby-wallet/bearby-extension/assets/7957498/dd26fb70-bc74-4d56-b4f1-fb7dafe88086)

**Comment by hicaru** [comment]
> Looks like the way private keys are generated changed sometime before mainnet. I installed Bearby about a year ago I think and didn't know about this change. So now I don't have access to the address that I sent my funds to because I don't have the private keys of the address Bearby shows. ![a](https://private-user-images.githubusercontent.com/7957498/342363946-dd26fb70-bc74-4d56-b4f1-fb7dafe88086.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNTMyNjksIm5iZiI6MTcyNDA1Mjk2OSwicGF0aCI6Ii83OTU3NDk4LzM0MjM2Mzk0Ni1kZDI2ZmI3MC1iYzc0LTRkNTYtYjRmMS1mYjdkYWZlODgwODYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTlUMDczNjA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTMyZTUwZjYyOTJjY2VmZjA3ZTFkYWFlNDcxNGQyYjM2Zjc1OTg1YWVhZTFiYjg0N2VkNzFmNTY2OGFhNjU5ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4dTJt-L9f1cBcrILZpcKbaR1vxnt7ugllG2r88bZ4KM)

Hello, yes the massa added version and network params into address, so now it different format, but any way you can back access it i think, if you will learn how works key pair generating and pack to massa address format
